import images from '@/public/assets/images/images';

export const tableContainerStyles = {
    overflowX: 'auto',
    borderRadius: '15px',
    '::-webkit-scrollbar': {
        height: '2px',
        backgroundColor: 'transparent',
        color: '#fff',
    },
    '::-webkit-scrollbar-thumb': {
        borderRadius: '10px',
        background:
            'linear-gradient(90deg, rgba(255,255,255,0) 2%, #22CDA660 50%, rgba(255,255,255,0) 98%)',
    },
    '::-webkit-scrollbar-track': {
        borderRadius: '10px',
        background: 'transparent',
    },
    mt: '24px',
    backgroundColor: 'transparent',
    boxShadow: 'none',
};

export const labels = [
    'Week 32/2023',
    'Week 32/2023',
    'Week 31/2023',
    'Week 30/2023',
    'Week 29/2023',
    'Week 28/2023',
    'Week 27/2023',
    'Week 26/2023',
    'Week 25/2023',
];

export const rows = [
    {
        id: 1,
        url: images.LeaderboardProfile,
        smallUrl: images.smallUrl,
        title: 'Flash 3.0FLASH',
        value: '165.15 ETH ',
        listingTime: '– Listing time:',
        date: '2023.07.31 19:34',
        progress: '80',
        view: 'View Pool',
    },
    {
        id: 2,
        url: images.LeaderboardProfile,
        smallUrl: images.smallUrl,
        title: 'Flash 3.0FLASH',
        value: '165.15 ETH ',
        listingTime: '– Listing time:',
        date: '2023.07.31 19:34',
        progress: '100',
        view: 'View Pool',
    },
    {
        id: 3,
        url: images.LeaderboardProfile,
        smallUrl: images.smallUrl,
        title: 'Flash 3.0FLASH',
        value: '165.15 ETH ',
        listingTime: '– Listing time:',
        date: '2023.07.31 19:34',
        progress: '20',
        view: 'View Pool',
    },
    {
        id: 4,
        url: images.LeaderboardProfile,
        smallUrl: images.smallUrl,
        title: 'Flash 3.0FLASH',
        value: '165.15 ETH ',
        listingTime: '– Listing time:',
        date: '2023.07.31 19:34',
        progress: '40',
        view: 'View Pool',
    },
    {
        id: 5,
        url: images.LeaderboardProfile,
        smallUrl: images.smallUrl,
        title: 'Flash 3.0FLASH',
        value: '165.15 ETH ',
        listingTime: '– Listing time:',
        date: '2023.07.31 19:34',
        progress: '100',
        view: 'View Pool',
    },
    {
        id: 6,
        url: images.LeaderboardProfile,
        smallUrl: images.smallUrl,
        title: 'Flash 3.0FLASH',
        value: '165.15 ETH ',
        listingTime: '– Listing time:',
        date: '2023.07.31 19:34',
        progress: '100',
        view: 'View Pool',
    },
    {
        id: 7,
        url: images.LeaderboardProfile,
        smallUrl: images.smallUrl,
        title: 'Flash 3.0FLASH',
        value: '165.15 ETH ',
        listingTime: '– Listing time:',
        date: '2023.07.31 19:34',
        progress: '100',
        view: 'View Pool',
    },
];
