export const AirdropABI = [
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'uint256', name: 'id', type: 'uint256' },
            {
                indexed: false,
                internalType: 'enum GempadAirdrop.Status',
                name: 'currentStatus',
                type: 'uint8',
            },
            { indexed: false, internalType: 'uint256', name: 'tokenBalance', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'timestamp', type: 'uint256' },
        ],
        name: 'AirdropCancelled',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'uint256', name: 'id', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'startTime', type: 'uint256' },
            {
                indexed: false,
                internalType: 'enum GempadAirdrop.Status',
                name: 'status',
                type: 'uint8',
            },
        ],
        name: 'AirdropStarted',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'uint256', name: 'id', type: 'uint256' },
            { indexed: false, internalType: 'address[]', name: 'participants', type: 'address[]' },
            { indexed: false, internalType: 'address', name: 'sender', type: 'address' },
        ],
        name: 'AllocationsRemoved',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'uint256', name: 'id', type: 'uint256' },
            { indexed: false, internalType: 'address', name: 'caller', type: 'address' },
            { indexed: false, internalType: 'bool', name: 'status', type: 'bool' },
        ],
        name: 'ExactAmountDisabled',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [{ indexed: false, internalType: 'uint8', name: 'version', type: 'uint8' }],
        name: 'Initialized',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: true, internalType: 'address', name: 'previousOwner', type: 'address' },
            { indexed: true, internalType: 'address', name: 'newOwner', type: 'address' },
        ],
        name: 'OwnershipTransferred',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'uint256', name: 'id', type: 'uint256' },
            { indexed: false, internalType: 'address[]', name: 'receiver', type: 'address[]' },
            { indexed: false, internalType: 'uint256[]', name: 'tokenAmount', type: 'uint256[]' },
        ],
        name: 'ParticipantsAdded',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'uint256', name: 'id', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'amount', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'fee', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'claimTime', type: 'uint256' },
        ],
        name: 'TokensCalimed',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [
            { indexed: false, internalType: 'uint256', name: 'id', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'tge', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'cycle', type: 'uint256' },
            { indexed: false, internalType: 'uint256', name: 'interval', type: 'uint256' },
            { indexed: false, internalType: 'bool', name: 'isVesting', type: 'bool' },
        ],
        name: 'VestingInfoSet',
        type: 'event',
    },
    {
        inputs: [
            { internalType: 'uint256', name: '_id', type: 'uint256' },
            { internalType: 'address', name: '_owner', type: 'address' },
            { internalType: 'address', name: '_tokenAddress', type: 'address' },
            { internalType: 'string', name: '_airdropName', type: 'string' },
            { internalType: 'address payable', name: '_feeReceiver', type: 'address' },
        ],
        name: '__GempadAirdrop_init',
        outputs: [],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address payable', name: 'receiver', type: 'address' },
            { internalType: 'string', name: 'serviceName', type: 'string' },
        ],
        name: '__ServicePayer_init',
        outputs: [],
        stateMutability: 'payable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address[]', name: 'receivers', type: 'address[]' },
            { internalType: 'uint256[]', name: 'tokenAmounts', type: 'uint256[]' },
        ],
        name: 'addParticipantsAndAllocation',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'airdropName',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'cancelAirdrop',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'claimTokens',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'disbableEnsureExactAmount',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'ensureExactAmount',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
        name: 'getClaimInfo',
        outputs: [
            {
                components: [
                    { internalType: 'uint256', name: 'claimed', type: 'uint256' },
                    { internalType: 'uint256', name: 'userAllocation', type: 'uint256' },
                    { internalType: 'uint256', name: 'lastClaimTime', type: 'uint256' },
                ],
                internalType: 'struct GempadAirdrop.ClaimData',
                name: '',
                type: 'tuple',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
        name: 'getClaimable',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
        name: 'getClaimedAmount',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getCurrentStatus',
        outputs: [{ internalType: 'enum GempadAirdrop.Status', name: 'status', type: 'uint8' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'getParticipants',
        outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
        name: 'getRemainingClaimabaleAmount',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: '_user', type: 'address' }],
        name: 'getUserAllocation',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'id',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'initialized',
        outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'owner',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'removeAllocations',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'renounceOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'uint256', name: '_TGEPercent', type: 'uint256' },
            { internalType: 'uint256', name: '_cyclePercent', type: 'uint256' },
            { internalType: 'uint256', name: '_cycleInterval', type: 'uint256' },
        ],
        name: 'setVestingInfo',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'uint256', name: '_startTime', type: 'uint256' }],
        name: 'startAirdrop',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'startTime',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'token',
        outputs: [{ internalType: 'contract IERC20Extented', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'totalClaimedTokens',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'totalTokens',
        outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
        name: 'transferOwnership',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'vestingInfo',
        outputs: [
            { internalType: 'uint256', name: 'TGEPercent', type: 'uint256' },
            { internalType: 'uint256', name: 'cyclePercent', type: 'uint256' },
            { internalType: 'uint256', name: 'cycleInterval', type: 'uint256' },
            { internalType: 'bool', name: 'isVestingEnabled', type: 'bool' },
        ],
        stateMutability: 'view',
        type: 'function',
    },
] as const;
