'use client';

import type { Metadata } from 'next';

import Footer from '@/components/Footer/Footer';
import Header from '@/components/Header/Header';
import { ScrollerMotion } from 'scroller-motion';
import { Container } from '@mui/material';

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

export default function LendingLayout({ children }: { children: React.ReactNode }) {
    return (
        <ScrollerMotion>
            <Container maxWidth="xl">
                <Header />
                {children}
                <Footer />
            </Container>
        </ScrollerMotion>
    );
}
